### ISSUE TITLE
Deprecate encryptToStore/decryptToStore

### ISSUE THREAD

**Issue by skeet70** [IronCoreLabs/ironweb#111]
We don't want to hold people's (encrypted) documents ourselves, and this hasn't seen significant usage, we should deprecate it before it does.

**Comment by BobWall23** [comment]
Only available in ironweb.

**Comment by BobWall23** [comment]
Just add the deprecation announcement. Should also modify the endpoints on ironcore-id at some point.

**Comment by skeet70** [comment]
A deprecation notice was added in #125. They'll be removed on the next major version bump.
