### ISSUE TITLE
Buffer is transfered to the frame on decrypt.

### ISSUE THREAD

**Issue by coltfred** [IronCoreLabs/ironweb#28]
In order to avoid copying potentially large amounts of data we currently transfer ownership of the underlying buffer when we encrypt/decrypt. This works well when we have a buffer that won't be reused, but does not work well if the buffer will be reused (as it causes all Uint8Arrays on top of that buffer to appear empty).

We should not transfer the buffers across to the frame to avoid callers seeing this kind of issue.

In order to work around this, callers can call `.slice(0)` on their Uint8Arrays before passing them to cause a copy to be made.

**Comment by ernieturner** [comment]
One option for a fix here would be to only do a copy to the frame when the buffer we have is only a view into the underlying buffer. That might be pretty confusing and cause odd behavior. A less performant but more complete solution would be to just copy on every clone into the frame.
