### ISSUE TITLE
Add option on document encrypt to not encrypt to current user

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironweb#29]
Add a new boolean option to `IronWeb.document.encrypt`, (grantToAuthor default true) to the options that allows callers to not encrypt to the user performing the operation, but only to those users/groups in the provided grant list. Validation must then be performed to verify that at least one user/group is being encrypted to, that is, this flag cannot be turned off if the list of grants is empty.

Not sure, but maybe this should also be added to `IronWeb.document.encryptToStore`?

See https://github.com/IronCoreLabs/ironoxide/issues/2

**Comment by coltfred** [comment]
@clintfred We should also add this to encryptToStore to maintain the same interface. This will surface as `grantToAuthor?: boolean` in the `DocumentCreateOptions`.

**Comment by clintfred** [comment]
Duplicate of https://github.com/IronCoreLabs/ironweb/issues/9
