### ISSUE TITLE
Support creating a document without granting access to the author

### ISSUE THREAD

**Issue by ernieturner** [IronCoreLabs/ironweb#9]
Add a new boolean flag (default true) on `document.create` which controls whether the author of the document will have the document be encrypted to them. The `document.create` call must share with at least one user/group, so if this option is false, the `grantList` must have at least one entry.

Also need to consume changes to how the document list, document get response structures can change if the author is requesting a document that they cannot decrypt.

As part of this ticket we should also update the UI so we can exercise this change in addition to adding UI to consume the change that lets users share documents with groups they are not a part of.

+ Sharing with a group you are not in
  - Add an arbitrary text box on document share to let users manually enter group IDs
+ Creating document without encrypting to current user
  - Add a checkbox on document create that lets the user opt out of sharing with themselves on create.

**Comment by coltfred** [comment]
The UI work has been moved to its own ticket. https://github.com/IronCoreLabs/ironweb/issues/32
